// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "bs-platform/lib/es6/curry.js";

var count = {
  contents: 0
};

function updateCount(countFn) {
  var countNode = document.getElementById("count");
  countNode.innerText = "Count is " + String(Curry._1(countFn, count));
  
}

function increment(n) {
  var initialVal = n.contents;
  n.contents = initialVal + 1 | 0;
  return n.contents;
}

function decrement(n) {
  var initialVal = n.contents;
  n.contents = initialVal - 1 | 0;
  return n.contents;
}

function getClassName(n) {
  if (n > 0) {
    return "count-positive";
  } else if (n < 0) {
    return "count-negative";
  } else {
    return "count-zero";
  }
}

function updateClass(param) {
  var countNode = document.getElementById("count");
  countNode.className = "count " + getClassName(count.contents);
  
}

var plusBtn = document.getElementById("plus-one");

var minusBtn = document.getElementById("minus-one");

plusBtn.addEventListener("click", (function (param) {
        updateCount(increment);
        return updateClass(undefined);
      }));

minusBtn.addEventListener("click", (function (param) {
        updateCount(decrement);
        return updateClass(undefined);
      }));

export {
  count ,
  updateCount ,
  increment ,
  decrement ,
  getClassName ,
  updateClass ,
  plusBtn ,
  minusBtn ,
  
}
/* plusBtn Not a pure module */
